#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s): ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

cd "$(dirname "$0")/.."

AWS_TFVARS="infra/aws/terraform.tfvars"
AZURE_TFVARS="infra/azure/terraform.tfvars"

# write_tfvars FILE KEY VALUE upserts `KEY = "VALUE"` into an HCL tfvars file
# (creates from the sibling .example first). Idempotent, like write_env.
write_tfvars() {
  local file="$1" key="$2" value="$3" tmp
  if [[ ! -f "$file" && -f "${file}.example" ]]; then
    cp "${file}.example" "$file"
    note "created $file from ${file}.example"
  fi
  touch "$file"
  tmp=$(mktemp)
  grep -vE "^[[:space:]]*${key}[[:space:]]*=" "$file" > "$tmp" || true
  printf '%s = "%s"\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$file"
  WRITTEN_ENV+=("${key} → ${file}")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$file"
}

banner "Sentinel multi-cloud attack targets: credential setup"

note "This wizard prepares infra/aws and infra/azure for a human-run"
note "'terraform apply'. It authenticates the cloud CLIs, fills the two"
note "terraform.tfvars files, and runs 'init' + 'plan' as a read-only"
note "readiness check. It never runs 'apply' or 'destroy'."

# ── Stage 1: AWS credentials ─────────────────────────────────────────────
stage "AWS: CLI credentials"
say "infra/aws uses the standard AWS credential chain; nothing goes in tfvars."
if command -v aws >/dev/null 2>&1 && aws sts get-caller-identity >/dev/null 2>&1; then
  note "already authenticated as: $(aws sts get-caller-identity --query Arn --output text 2>/dev/null || echo unknown)"
else
  command -v aws >/dev/null 2>&1 || warn "the 'aws' CLI is not installed - install it, then re-run this wizard."
  step "For a long-lived IAM user: run 'aws configure' and paste an access key + secret."
  step "For SSO / Identity Center: run 'aws configure sso' once, then 'aws sso login'."
  open_url "https://console.aws.amazon.com/iam/home#/security_credentials"
  if command -v aws >/dev/null 2>&1 && confirm "Run 'aws configure' now?"; then
    aws configure || true
  fi
  if command -v aws >/dev/null 2>&1 && aws sts get-caller-identity >/dev/null 2>&1; then
    note "authenticated as: $(aws sts get-caller-identity --query Arn --output text 2>/dev/null || echo unknown)"
  else
    SKIPPED+=("AWS CLI authentication (aws sts get-caller-identity still fails)")
    warn "still not authenticated - fix this before 'terraform apply' on infra/aws."
  fi
fi
pause

# ── Stage 2: Azure credentials ──────────────────────────────────────────
stage "Azure: CLI credentials"
say "infra/azure uses the standard Azure credential chain; nothing goes in tfvars."
if command -v az >/dev/null 2>&1 && az account show >/dev/null 2>&1; then
  note "already logged in to subscription: $(az account show --query name --output tsv 2>/dev/null || echo unknown)"
else
  command -v az >/dev/null 2>&1 || warn "the 'az' CLI is not installed - install it, then re-run this wizard."
  if command -v az >/dev/null 2>&1 && confirm "Run 'az login' now? (opens a browser)"; then
    az login --only-show-errors >/dev/null || true
  fi
  if command -v az >/dev/null 2>&1 && az account show >/dev/null 2>&1; then
    note "logged in to subscription: $(az account show --query name --output tsv 2>/dev/null || echo unknown)"
  else
    SKIPPED+=("Azure CLI authentication (az account show still fails)")
    warn "still not logged in - fix this before 'terraform apply' on infra/azure."
  fi
fi
pause

# ── Stage 3: Tailscale auth key ─────────────────────────────────────────
stage "Tailscale: auth key for the targets"
say "cloud-init on each target runs 'tailscale up --authkey=...' to join the tailnet."
open_url "https://login.tailscale.com/admin/settings/keys"
step "Click 'Generate auth key'."
step "Enable 'Reusable' (both targets share it) and, recommended, 'Ephemeral'"
step "  so the nodes auto-remove from the tailnet when destroyed. Then 'Generate key'."
step "Copy the key (starts tskey-auth-)."
ask_secret TS_AUTHKEY "Paste the Tailscale auth key:"
write_tfvars "$AWS_TFVARS"   tailscale_authkey "$TS_AUTHKEY"
write_tfvars "$AZURE_TFVARS" tailscale_authkey "$TS_AUTHKEY"
pause

# ── Stage 4: Elastic enrolment ─────────────────────────────────────────
stage "Elastic: ingest endpoint for auditbeat"
say "The targets ship auditbeat straight to the live OCI Elastic over Tailscale."
step "Use the MagicDNS name if the targets can resolve it, else the tailnet IP:"
note "  e.g. http://sentinel-elastic:9200  or  http://100.x.y.z:9200"
ask ELASTIC_URL_IN "Elastic URL [http://sentinel-elastic:9200]:"
[[ -z "$ELASTIC_URL_IN" ]] && ELASTIC_URL_IN="http://sentinel-elastic:9200"
step "elastic_password is the 'elastic' superuser password from infra/compose/elastic/.env"
note "  (on the sentinel-elastic VM). It is written only to the gitignored tfvars files."
ask_secret ELASTIC_PASSWORD_IN "Paste the elastic superuser password:"
write_tfvars "$AWS_TFVARS"   elastic_url      "$ELASTIC_URL_IN"
write_tfvars "$AWS_TFVARS"   elastic_password "$ELASTIC_PASSWORD_IN"
write_tfvars "$AZURE_TFVARS" elastic_url      "$ELASTIC_URL_IN"
write_tfvars "$AZURE_TFVARS" elastic_password "$ELASTIC_PASSWORD_IN"
pause

# ── Stage 5: SSH public key ────────────────────────────────────────────
stage "SSH: public key installed on the targets"
say "The key pair used for the fallback SSH path (tailscale ssh is the normal one)."
ask SSH_PUB_PATH "Path to your SSH public key [~/.ssh/id_ed25519.pub]:"
[[ -z "$SSH_PUB_PATH" ]] && SSH_PUB_PATH="~/.ssh/id_ed25519.pub"
_expanded="${SSH_PUB_PATH/#\~/$HOME}"
if [[ -f "$_expanded" ]]; then
  note "found: $_expanded"
else
  SKIPPED+=("SSH public key not found at $_expanded - create one with ssh-keygen -t ed25519")
  warn "no file at $_expanded - 'terraform plan' will fail until this exists."
fi
write_tfvars "$AWS_TFVARS"   ssh_public_key_path "$SSH_PUB_PATH"
write_tfvars "$AZURE_TFVARS" ssh_public_key_path "$SSH_PUB_PATH"
pause

# ── Stage 6: readiness check (init + plan only, never apply) ────────────
stage "Terraform: init + plan readiness check"
say "Runs 'terraform init' then 'terraform plan' for both roots. Read-only:"
say "it queries the cloud APIs but changes nothing. 'apply' stays a manual step."
if confirm "Run init + plan for infra/aws and infra/azure now?"; then
  for root in infra/aws infra/azure; do
    printf '\n'
    step "=== $root ==="
    if terraform -chdir="$root" init -input=false >/dev/null; then
      note "init ok"
    else
      SKIPPED+=("terraform init failed for $root")
      warn "init failed for $root - see output above."
      continue
    fi
    if terraform -chdir="$root" plan -input=false -no-color; then
      note "plan ok for $root"
    else
      SKIPPED+=("terraform plan failed for $root - resolve before apply")
      warn "plan failed for $root."
    fi
  done
else
  SKIPPED+=("terraform init + plan readiness check (skipped - run it before apply)")
fi
pause

finish

note "Next (human-run, not this wizard):"
note "  terraform -chdir=infra/aws apply     # then infra/azure"
note "  TARGETS=\"sentinel-target-aws sentinel-target-azure\" ./scripts/run-e2e-demo.sh"
note "  terraform -chdir=infra/aws destroy   # after the demo, to stop the burn"
